default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ost-api_dev

test:
  <<: *default
  database: ost-api_test

production:
  <<: *default
  database: ost-api_prod
